apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket-t3a
spec:
  amiFamily: Bottlerocket
  role: "KarpenterNodeRole-finishline-dev-eks" # The role we created with Terragrunt
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "finishline-dev-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "finishline-dev-eks"
  amiSelectorTerms:
    - alias: bottlerocket@v1.30
  tags:
    Project: "FinishLine2026"
    karpenter.sh/discovery: "finishline-dev-eks"
