apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: bottlerocket-t3a
spec:
  amiFamily: Bottlerocket

  # MUST be the full IAM role ARN
  role: arn:aws:iam::590183777783:role/finishline-dev-eks-karpenter-node-role

  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/finishline-dev-eks: owned
    - tags:
        kubernetes.io/role/internal-elb: "1"

  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/finishline-dev-eks: owned

  tags:
    karpenter.sh/discovery: finishline-dev-eks
    Project: "FinishLine2026"
